### ISSUE TITLE
Add counting site name attribute

### ISSUE THREAD

**Issue by vdieulesaint** [etalab/schema-comptage-mobilites-site#22]
Hi, 

I spotted an issue. Indeed, thhe counting site name is not present in v0.1.0 but was present in the[ initial design](https://docs.google.com/spreadsheets/d/18aAUucg5FGlvXug_bynrY7Kr_dMGUS6Z85xsJohhnLE/edit#gid=109583725) as a mandatory property.
I guess it was an oversight when the initial was released.
Please, could you add it as designed.

Vincent

**Comment by thbar** [comment]
Merci @vdieulesaint ! Corrigé dans #23 et nous allons refaire une release.

**Comment by thbar** [comment]
Traité dans https://github.com/etalab/schema-comptage-mobilites-site/releases/tag/v0.2.0.
